#!/usr/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap  20
bspc config top_padding 12
bspc config bottom_padding -10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "AFA992"
bspc config normal_border_color  "323C41F"
bspc config pointer_motion_interval 80

bspc rule -a Zathura state=tiled  # Run Zathura in Tiled Mode by Default

dunst &  # Turn Dunst On (custom notifications)
picom -b &  # Turn Picom On (window compositor)
nitrogen --restore &  # Turn Nitrogen On (wallpaper setter)
xsetroot -cursor_name left_ptr &  # Set Custom Cursor

~/.config/polybar/launch.sh  # Launch Polybar
