#!/usr/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 0
bspc config window_gap  20
bspc config top_padding 12
bspc config bottom_padding -10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "AFA992"
bspc config normal_border_color  "323c41f"

dunst &  # turn dunst on (custom notifications)
picom -b --experimental-backends &  # turn picom on (window compositor)
nitrogen --restore &  # turn nitrogen on (wallpapers)
xsetroot -cursor_name left_ptr &  # set custom cursor

~/.config/polybar/launch.sh  # launch polybar
