require("barbecue").setup({
  exclude_filetypes = {'packer', 'neo-tree', "dashboard", "TelescopePrompt", "DiffviewFilePanel", "diff", "undotree"},
        theme = { normal = { fg = "#C6C0A9", bold = true },

          context_file = { fg = "#535F5C" },
          context_module = { fg = "#535F5C" },
          context_namespace = { fg = "#535F5C" },
          context_package = { fg = "#535F5C" },
          context_class = { fg = "#535F5C" },
          context_method = { fg = "#535F5C" },
          context_property = { fg = "#535F5C" },
          context_field = { fg = "#535F5C" },
          context_constructor = { fg = "#535F5C" },
          context_enum = { fg = "#535F5C" },
          context_interface = { fg = "#535F5C" },
          context_function = { fg = "#535F5C" },
          context_variable = { fg = "#535F5C" },
          context_constant = { fg = "#535F5C" },
          context_string = { fg = "#535F5C" },
          context_number = { fg = "#535F5C" },
          context_boolean = { fg = "#535F5C" },
          context_array = { fg = "#535F5C" },
          context_object = { fg = "#535F5C" },
          context_key = { fg = "#535F5C" },
          context_null = { fg = "#535F5C" },
          context_enum_member = { fg = "#535F5C" },
          context_struct = { fg = "#535F5C" },
          context_event = { fg = "#535F5C" },
          context_operator = { fg = "#535F5C" },
          context_type_parameter = { fg = "#535F5C" },
        },
      })
